INSERT INTO student (FIRST_NAME, LAST_NAME) VALUES ('bob', 'bobsen');
INSERT INTO student (FIRST_NAME, LAST_NAME) VALUES ('ib', 'ibsen');
INSERT INTO student (FIRST_NAME, LAST_NAME) VALUES ('ida', 'idasen');
INSERT INTO student (FIRST_NAME, LAST_NAME) VALUES ('lars', 'larssen');

INSERT INTO teacher (FIRST_NAME, LAST_NAME) VALUES ('Rosa', 'Rosasen');
INSERT INTO teacher (FIRST_NAME, LAST_NAME) VALUES ('Pia', 'Piasen');
INSERT INTO teacher (FIRST_NAME, LAST_NAME) VALUES ('Finn', 'Finnsen');

INSERT INTO course (COURSE_NAME) VALUES ('Java');
INSERT INTO course (COURSE_NAME) VALUES ('Database');
INSERT INTO course (COURSE_NAME) VALUES ('UI');

INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (1, 1);
INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (2, 1);

INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (2, 2);
INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (3, 2);

INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (1, 3);
INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (3, 3);

INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (1, 4);
INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (2, 4);
INSERT INTO course_students(COURSES_ID, STUDENTS_ID) VALUES (3, 4);

INSERT INTO teacher_courses(TEACHER_ID, COURSES_ID) VALUES (1, 1);
INSERT INTO teacher_courses(TEACHER_ID, COURSES_ID) VALUES (1, 3);
INSERT INTO teacher_courses(TEACHER_ID, COURSES_ID) VALUES (3, 2);